### ISSUE TITLE
Need help on Cmake Error:

### ISSUE THREAD

**Issue by supremethememe** [lithiumtoast/pempo#2]
What do i do to fix this? Trying to configure but Make keeps saying this:

<img width="668" alt="Screen Shot 2019-03-16 at 3 32 56 PM" src="https://user-images.githubusercontent.com/39014019/54480617-df982200-4800-11e9-8025-8d48f2a3e116.png">

and this is is where the error is:

<img width="641" alt="Screen Shot 2019-03-16 at 3 31 54 PM" src="https://user-images.githubusercontent.com/39014019/54480600-ac559300-4800-11e9-8c97-5af288a5f9e3.png">

**Comment by lithiumtoast** [comment]
It's been quite some time since I did this project. At the time, and even today, I use terminal for most development. On macOS it's fairly straight forward:

1. Install [Homebrew](https://brew.sh).
2. Install CMake: `brew install cmake`
3. Build project from terminal. I like to do this by doing a CMake out-of-source-build: `cmake -H. -Bbin/Release -DCMAKE_BUILD_TYPE=Release`

**Comment by supremethememe** [comment]
Thank you 🙏🏻

**Comment by supremethememe** [comment]
Do you have any additional tips or instructions because I am very new to this

**Comment by supremethememe** [comment]
can't make. no configure file included in source code. can you release Pempo source code with configure file? Thanks
